[package]
name = "acryl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "1.0.0-alpha.4"
acryl_pdf = { path = "./acryl_pdf" }