[package]
name = "acryl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acryl_pdf = { path = "./acryl_pdf" }
acryl_parser = { path = "./acryl_parser" }
acryl_core = { path = "./acryl_core" }