[package]
name = "acryl_layout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acryl_core = { path = "../acryl_core" }
acryl_pdf = { path = "../acryl_pdf" }
rustybuzz = "0.13.0"